"""
Django settings for todo project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
import re
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SHARED_API_ENV_FILE = (
    BASE_DIR / "api" / "tmdb-streaming" / "environments" / ".env"
)


def _read_shared_env_value(key_name):
    if not SHARED_API_ENV_FILE.exists():
        return ""

    content = SHARED_API_ENV_FILE.read_text(encoding="utf-8", errors="ignore")
    key_variants = [key_name, key_name.lower()]
    for raw_line in content.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or line in {"vars {", "}"}:
            continue

        for variant in key_variants:
            env_match = re.match(rf"^{re.escape(variant)}\s*=\s*(.+)$", line)
            if env_match:
                value = env_match.group(1).strip()
                return value.strip("'\"")

            legacy_match = re.match(rf"^{re.escape(variant)}\s*:\s*\"?([^\"\n]+)\"?$", line)
            if legacy_match:
                return legacy_match.group(1).strip()

    return ""


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=8e&h2naz6*na6mne4y8l1m@rr=(igde^7rz2cmal)r_o)raoo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [host.strip() for host in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks.apps.TasksConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'todo.middleware.SimpleCORSMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'todo.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'todo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'todo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'list'
LOGOUT_REDIRECT_URL = 'login'

AUTHENTICATION_BACKENDS = [
    "tasks.auth_backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE", "false").lower() == "true"
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE", "false").lower() == "true"
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"

SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "no-reply@watch-list.local")

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
    if origin.strip()
]

# FranceConnect v1 (OIDC) configuration.
FRANCECONNECT_CLIENT_ID = os.environ.get(
    "FRANCECONNECT_CLIENT_ID",
    _read_shared_env_value("FRANCECONNECT_CLIENT_ID"),
).strip()
FRANCECONNECT_CLIENT_SECRET = os.environ.get(
    "FRANCECONNECT_CLIENT_SECRET",
    _read_shared_env_value("FRANCECONNECT_CLIENT_SECRET"),
).strip()
FRANCECONNECT_AUTHORIZE_URL = os.environ.get(
    "FRANCECONNECT_AUTHORIZE_URL",
    _read_shared_env_value("FRANCECONNECT_AUTHORIZE_URL")
    or "https://fcp-low.integ01.dev-franceconnect.fr/api/v2/authorize",
).strip()
FRANCECONNECT_TOKEN_URL = os.environ.get(
    "FRANCECONNECT_TOKEN_URL",
    _read_shared_env_value("FRANCECONNECT_TOKEN_URL")
    or "https://fcp-low.integ01.dev-franceconnect.fr/api/v2/token",
).strip()
FRANCECONNECT_USERINFO_URL = os.environ.get(
    "FRANCECONNECT_USERINFO_URL",
    _read_shared_env_value("FRANCECONNECT_USERINFO_URL")
    or "https://fcp-low.integ01.dev-franceconnect.fr/api/v2/userinfo",
).strip()
FRANCECONNECT_SCOPE = os.environ.get(
    "FRANCECONNECT_SCOPE",
    _read_shared_env_value("FRANCECONNECT_SCOPE") or "openid profile email",
).strip()
FRANCECONNECT_ACR_VALUES = os.environ.get(
    "FRANCECONNECT_ACR_VALUES",
    _read_shared_env_value("FRANCECONNECT_ACR_VALUES") or "eidas1",
).strip()
FRANCECONNECT_REDIRECT_URI = os.environ.get(
    "FRANCECONNECT_REDIRECT_URI",
    _read_shared_env_value("FRANCECONNECT_REDIRECT_URI"),
).strip()
FRANCECONNECT_ENABLED = (
    os.environ.get(
        "FRANCECONNECT_ENABLED",
        _read_shared_env_value("FRANCECONNECT_ENABLED") or "true",
    ).lower()
    == "true"
    and bool(FRANCECONNECT_CLIENT_ID and FRANCECONNECT_CLIENT_SECRET)
)

TMDB_READ_ACCESS_TOKEN = os.environ.get(
    "TMDB_READ_ACCESS_TOKEN",
    _read_shared_env_value("TMDB_READ_ACCESS_TOKEN"),
)
TMDB_LANGUAGE = os.environ.get(
    "TMDB_LANGUAGE",
    _read_shared_env_value("TMDB_LANGUAGE") or "fr-FR",
)
TMDB_WATCH_REGION = os.environ.get(
    "TMDB_WATCH_REGION",
    _read_shared_env_value("TMDB_WATCH_REGION") or "US",
)
