# Generated by Django 4.2.26 on 2026-02-17 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_task_provider_service_id_task_provider_slug_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_provider_series',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('user', 'provider_service_id', 'tmdb_series_id'), name='unique_user_provider_series'),
        ),
    ]
