# Generated by Django 4.2.26 on 2026-02-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_user_userprofile_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
